/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { cottageScene } from '../assets'

const Cottage = (props) => {

  const { nodes, materials } = useGLTF(cottageScene)
  
  return (
    <group 
      {...props}
      rotation = {[0.1, 0.7, 0]}
    >
      <mesh
        geometry={nodes.Balkon_beton_002.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Balky_005.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Balky_006.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Balky_007.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Balky_008.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Bassein001.geometry}
        material={materials['Material #35']}
      />
      <mesh
        geometry={nodes.Beton_003.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Bordur001.geometry}
        material={materials['Material #29']}
      />
      <mesh
        geometry={nodes.Box076.geometry}
        material={materials['Material #63']}
      />
      <mesh
        geometry={nodes.Box077.geometry}
        material={materials['Material #63']}
      />
      <mesh
        geometry={nodes.Box078.geometry}
        material={materials['Material #63']}
      />
      <mesh
        geometry={nodes.Box079.geometry}
        material={materials['Material #64.001']}
      />
      <mesh
        geometry={nodes.Box080.geometry}
        material={materials['Material #64.001']}
      />
      <mesh
        geometry={nodes.Box081.geometry}
        material={materials['Material #29']}
      />
      <mesh
        geometry={nodes.Box082.geometry}
        material={materials['Material #63']}
      />
      <mesh
        geometry={nodes.Box083.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Box084.geometry}
        material={materials['Material #81']}
      />
      <mesh
        geometry={nodes.Box085.geometry}
        material={materials['Material #81']}
      />
      <mesh
        geometry={nodes.Box086.geometry}
        material={materials['Material #81']}
      />
      <mesh
        geometry={nodes.Box087.geometry}
        material={materials['Material #81']}
      />
      <mesh
        geometry={nodes.Box090.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Box091.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Box092.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Box096.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Box097.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box098.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box099.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box100.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box101.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box102.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box103.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box104.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box105.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box106.geometry}
        material={materials['Material #114']}
      />
      <mesh
        geometry={nodes.Box107.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box108.geometry}
        material={materials['Material #114']}
      />
      <mesh
        geometry={nodes.Box109.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box110.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box111.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box112.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Box113.geometry}
        material={materials['Material #64']}
      />
      <mesh
        geometry={nodes.Box114.geometry}
        material={materials['Material #114']}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material #83']}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material #81']}
      />
      <mesh
        geometry={nodes.Box088.geometry}
        material={materials['Material #85']}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Doroga001.geometry}
        material={materials['Material #47']}
      />
      <mesh
        geometry={nodes.Ruckha001.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Vhodnaya_dver001.geometry}
        material={materials['Material #62']}
      />
      <mesh
        geometry={nodes.Garag001.geometry}
        material={materials['Material #83']}
      />
      <mesh
        geometry={nodes.Gazon001.geometry}
        material={materials['Material #34']}
      />
      <mesh
        geometry={nodes.Krysha001.geometry}
        material={materials['Material #29']}
      />
      <mesh
        geometry={nodes.Object009.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.kusty001.geometry}
        material={materials['Material #48']}
      />
      <mesh
        geometry={nodes.Lejak_003.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Lejak001.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Object010.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Object011.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Object012.geometry}
        material={materials['Material #2']}
      />
      <mesh
        geometry={nodes.Object013.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Object014.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Object015.geometry}
        material={materials['Material #63']}
      />
      <mesh
        geometry={nodes.Okna_1_etaj001.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Okna_2_etaj001.geometry}
        material={materials['Material #3']}
      />
      <mesh
        geometry={nodes.Okna_steklo_2_etaj001.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Perekritie_003.geometry}
        material={materials['Material #65']}
      />
      <mesh
        geometry={nodes.Perekritie_004.geometry}
        material={materials['Material #65']}
      />
      <mesh
        geometry={nodes.Perila_balkon001.geometry}
        material={materials['Material #88']}
      />
      <mesh
        geometry={nodes.Perila003.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Perila004.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Perila005.geometry}
        material={materials['Material #88']}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials['Material #69']}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Plitka_pol001.geometry}
        material={materials['Material #31']}
      />
      <mesh
        geometry={nodes.Pol_2_etaj001.geometry}
        material={materials['Material #69']}
      />
      <mesh
        geometry={nodes.Steklo_Balkon_003.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Steklo_balkon001.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Steklo_okna_1_etaj001.geometry}
        material={materials['Material #61']}
      />
      <mesh
        geometry={nodes.Steny_1_etaj001.geometry}
        material={materials['Material #2']}
      />
      <mesh
        geometry={nodes.Steny_2_etaj001.geometry}
        material={materials['Material #2']}
      />
      <mesh
        geometry={nodes.Stol006.geometry}
        material={materials['Material #38']}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={materials['Material #115']}
      />
      <mesh
        geometry={nodes.Box089.geometry}
        material={materials['Material #82']}
      />
      <mesh
        geometry={nodes.Плоскость.geometry}
        material={materials.Материал}
      />
      <mesh
        geometry={nodes.Object014001.geometry}
        material={materials['Material #61']}
        position={[0.026, 0, 0]}
      />
      <mesh
        geometry={nodes.Balky_007001.geometry}
        material={materials['Material #38.001']}
        position={[4.273, 4.713, -0.022]}
      />
      <mesh
        geometry={nodes.Balky_007002.geometry}
        material={materials['Material #38.002']}
        position={[4.273, 4.713, -3.952]}
      />
      <mesh
        geometry={nodes.Balky_007003.geometry}
        material={materials['Material #38.003']}
        position={[1.615, 4.713, -7.723]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Balky_007004.geometry}
        material={materials['Material #38.004']}
        position={[-2.945, 4.713, -7.723]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Balky_007005.geometry}
        material={materials['Material #38.005']}
        position={[-6.494, 4.713, -2.859]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Balky_007006.geometry}
        material={materials['Material #38.006']}
        position={[-6.494, 4.713, -6.294]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Balky_007007.geometry}
        material={materials['Material #38.007']}
        position={[-6.494, 4.713, 2.741]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Balky_007008.geometry}
        material={materials['Material #38.008']}
        position={[1.003, 4.7, 6.319]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Balky_007009.geometry}
        material={materials['Material #38.009']}
        position={[-1.99, 4.7, 6.319]}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/cottage.glb')

export default Cottage